# Generated by Django 5.0.7 on 2024-07-15 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 15, 9, 52, 42, 632337, tzinfo=datetime.timezone.utc)),
        ),
    ]
